## `try/catch`
* `try`: 保护代码块，有异常时，异常将被抛给 `catch` 代码块；
* `catch`: 异常代码块，当 `try` 中有异常，此时想要执行什么操作；
* `finally`: 不管是否发生异常，都会执行的代码块，常用于 `IO` 操作。
```java
// 异常
int a = 0;
int b = 1;
try {
    System.out.println(b / a);
} catch (Throwable e) {
    System.out.println("执行异常块代码");
    System.out.println(e); // java.lang.ArithmeticException: / by zero
} finally {
    System.out.println("不管是否异常，都会执行的代码块！");
}
```

### 多重校验
> 必须按照类从低 => 高的顺序书写 `catch` 块；覆盖范围广的写在前面，会把错误拦截下来，不执行后面的catch块。就类似与，在 方法中写了 return，后面的代码就不执行了，编译会报错。
```java
int a = 1;
int b = 0;

try {
    System.out.println(a / b);
} catch (IndexOutOfBoundsException err) {
    // IndexOutOfBoundsException 数组越界 异常类是 Exception 子类
    System.out.println("IndexOutOfBoundsException");
} catch (Exception err) {
    // Exception 比 数组越界类覆盖范围要高，所以放在后面，不然无法执行到 数组越界那个 catch 块
    System.out.println("Exception");
} catch (Throwable err) {
    // Throwable 是异常的基类，覆盖范围最广，所以要放在最下面。
    System.out.println("Throwable");
} finally {
    System.out.println("finally");
}
```


## `throws/throw` 关键字：
*  `throw` 关键字用来抛出一个异常；
* `throws` 关键字放在方法签名的尾部。
```java
// throws 用于方法中可能存在得异常
void doSomething(int a) throws Exception1,Exception3{
  try{
    // ....
  } catch(Exception1 e){
    // 抛出一个异常
    throw e;
  } catch(Exception2 e){
    System.out.println("出错了！");
  }
  if(a!=b)
    // 抛出一个自定义异常
    throw new  Exception3("自定义异常");
}

```